name: Deploy to GitHub Pages

on:
    push:
        branches: ["main"]

permissions:
    contents: write
    pages: write
    id-token: write

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: "npm"

            - name: Install
              run: npm ci

            - name: Build SDK
              run: npm run build

            - name: Build demo
              run: |
                  mkdir -p demo-dist
                  cp demo/index.html demo-dist/
                  cp dist/captcha-sweeper.es.js demo-dist/

            - name: Setup Pages
              uses: actions/configure-pages@v4

            - name: Upload artifact
              uses: actions/upload-pages-artifact@v3
              with:
                  path: ./demo-dist

            - name: Deploy to GitHub Pages
              uses: actions/deploy-pages@v4
